name: Docker PyTest CI Pipeline

on: [push, pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code from Repository
        uses: actions/checkout@v4

      - name: Run Tests with Docker Compose
        run: docker compose up --abort-on-container-exit

      - name: Upload Test Report Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: pytest-execution-report
          path: reports/report.html
